amcl:
  ros__parameters:
    use_sim_time: True
    base_frame_id: "/simple_drone/base_link"
    global_frame_id: "map"
    odom_frame_id: "/simple_drone/odom"
    robot_model_type: "nav2_amcl::OmniMotionModel"
    transform_tolerance: 1.0
    scan_topic: /simple_drone/scan

bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /simple_drone/odom
    bt_loop_duration: 10
    default_server_timeout: 20
    wait_for_service_timeout: 1000
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_smooth_path_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_is_path_valid_condition_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_time_expired_condition_bt_node

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 10.0
    min_x_velocity_threshold: 0.01
    min_y_velocity_threshold: 0.01
    min_theta_velocity_threshold: 0.01
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 1.5
      min_turning_radius: 0.1
      transform_tolerance: 0.2
      use_velocity_scaled_lookahead_dist: true

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: /simple_drone/odom
      robot_base_frame: /simple_drone/base_link
      use_sim_time: True
      rolling_window: true
      width: 10.0
      height: 10.0
      resolution: 0.2
      robot_radius: 0.5
      plugins: ["voxel_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 2.5
        inflation_radius: 1.0
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.1
        z_voxels: 20
        max_obstacle_height: 5.0
        mark_threshold: 0
        observation_sources: lidar
        lidar:
          topic: /simple_drone/lidar
          max_obstacle_height: 5.0
          clearing: True
          marking: True
          data_type: "PointCloud2"
          raytrace_max_range: 10.0
          raytrace_min_range: 0.5
          obstacle_max_range: 8.0
          obstacle_min_range: 0.3

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: /simple_drone/base_link
      use_sim_time: True
      robot_radius: 0.5
      resolution: 0.2
      track_unknown_space: true
      plugins: ["static_layer", "voxel_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.1
        z_voxels: 20
        max_obstacle_height: 5.0
        mark_threshold: 0
        observation_sources: lidar
        lidar:
          topic: /simple_drone/lidar
          max_obstacle_height: 5.0
          clearing: True
          marking: True
          data_type: "PointCloud2"
          raytrace_max_range: 10.0
          raytrace_min_range: 0.5
          obstacle_max_range: 8.0
          obstacle_min_range: 0.3
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 2.5
        inflation_radius: 1.0

goal_checker:
  ros__parameters:
    plugin: "nav2_motion_primitives::SimpleGoalChecker"
    xy_goal_tolerance: 0.5
    yaw_goal_tolerance: 0.3
    stateful: True

map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: ""

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: true
      allow_unknown: true

smoother_server:
  ros__parameters:
    use_sim_time: True
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: True

robot_state_publisher:
  ros__parameters:
    use_sim_time: True

waypoint_follower:
  ros__parameters:
    use_sim_time: True
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200

velocity_smoother:
  ros__parameters:
    use_sim_time: True
    smoothing_frequency: 20.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [1.5, 1.5, 1.0]
    min_velocity: [-1.5, -1.5, -1.0]
    max_accel: [3.0, 3.0, 3.0]
    max_decel: [-3.0, -3.0, -3.0]
    odom_topic: "/simple_drone/odom"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0
